language: python

python:
  - "3.5"
  - "3.4"
  - "2.7"

addons:
  postgresql: "9.5"

env:
  - DJANGO="django>=1.11,<2.0"
  - DJANGO="django>=1.10,<1.11"
  - DJANGO="django>=1.9,<1.10"
  - DJANGO="django>=1.8,<1.9"

services:
  - postgresql

install:
  - pip install $DJANGO
  - pip install -r requirements.pip
branches:
  only:
    - master

script:
  - django-admin test --settings=testing.settings testing.pg_array_fields.tests

before_script:
  - createdb test
  - export PYTHONPATH="$(pwd):$PYTHONPATH"

notifications:
  email:
    recipients:
      - niwi@niwi.be
    on_success: change
    on_failure: change
